version: 1
disable_existing_loggers: False
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  runtimeFile:
    class: logging.handlers.RotatingFileHandler
    filename: F:\ProjectD\SchooWork\log\runtime.log
    maxBytes: 10485760 # 10M
    backupCount: 50
    encoding: utf-8
    formatter: basic
  safeFile:
    class: logging.handlers.RotatingFileHandler
    filename: F:\ProjectD\SchooWork\log\safe.log
    maxBytes: 10485760 # 10M
    backupCount: 50
    encoding: utf-8
    formatter: basic
formatters:
  basic:
    format: "%(levelname)-8s [%(asctime)s] [pid:%(process)s] [filename:%(filename)s] [fun:%(funcName)s] [lineno:%(lineno)d] [%(name)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  simpleformat:
    format: "%(levelname)-8s [%(asctime)s] %(message)s"
loggers:
  runtime:
    handlers: [runtimeFile]
    level: DEBUG
    propagete: False # 日志传播
  safe:
    handlers: [safeFile]
    level: DEBUG
    propagete: False
  root:
    handlers: [console]
    level: DEBUG


# http://python.usyiyi.cn/translate/python_352/library/logging.config.html
